# Generated by Django 3.2.9 on 2021-11-19 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True, verbose_name='Название купона')),
                ('coupon_valid_form', models.DateTimeField(verbose_name='Начало действия купона')),
                ('coupon_valid_to', models.DateTimeField(verbose_name='Время окончания купона')),
                ('coupon_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coupon_active', models.BooleanField(verbose_name='Активный купон?')),
            ],
        ),
    ]
